title: Atomizer
description: "A CSS utility for component-based websites"
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      githubDocsPath: "https://github.com/acss-io/acss-site/tree/master/docs/"
plugins:
  - jekyll-seo-tag
