version: '3'
services:
    jekyll:
        image: jekyll/jekyll:3.8
        environment:
            - JEKYLL_ENV=development
        command: bash -c "cd docs && jekyll serve --watch --incremental --config _config.yml --host 0.0.0.0"
        ports:
            - 4000:4000
        volumes:
            - .:/srv/jekyll
        restart: unless-stopped
