module.exports = {
    c: 'color',
    cb: 'color-burn',
    cd: 'color-dodge',
    d: 'darken',
    di: 'difference',
    e: 'exclusion',
    h: 'hue',
    hl: 'hard-light',
    l: 'lighten',
    lu: 'luminosity',
    m: 'multiply',
    n: 'normal',
    o: 'overlay',
    s: 'saturation',
    sc: 'screen',
    sl: 'soft-light',
};
